services:
  server:
    image: ${SERVER_IMAGE}
    container_name: watchlist-server
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      PORT: 3000
      FE_BASE_URL: ${FE_BASE_URL}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
    ports:
      - '${SERVER_PORT:-3000}:3000'

  watchlist:
    image: ${FRONTEND_IMAGE}
    container_name: watchlist-frontend
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - '${FRONTEND_PORT:-80}:80'
